!Panoptica_Evaluator
decision_metric: null
decision_threshold: null
edge_case_handler: !EdgeCaseHandler
  empty_list_std: !EdgeCaseResult NAN
  listmetric_zeroTP_handling:
    !Metric DSC: !MetricZeroTPEdgeCaseHandling {empty_prediction_result: !EdgeCaseResult ZERO,
      empty_reference_result: !EdgeCaseResult ZERO, no_instances_result: !EdgeCaseResult NAN,
      normal: !EdgeCaseResult ZERO}
    !Metric NSD: !MetricZeroTPEdgeCaseHandling {empty_prediction_result: !EdgeCaseResult INF,
      empty_reference_result: !EdgeCaseResult INF, no_instances_result: !EdgeCaseResult NAN,
      normal: !EdgeCaseResult INF}
    !Metric HD95: !MetricZeroTPEdgeCaseHandling {empty_prediction_result: !EdgeCaseResult INF,
      empty_reference_result: !EdgeCaseResult INF, no_instances_result: !EdgeCaseResult NAN,
      normal: !EdgeCaseResult INF}
expected_input: !InputType SEMANTIC
global_metrics: [!Metric DSC,!Metric NSD, !Metric HD95]
instance_approximator: !ConnectedComponentsInstanceApproximator {cca_backend: null}
instance_matcher: !MaxBipartiteMatching {matching_metric: !Metric DSC,
  matching_threshold: 0.000001}
instance_metrics: [!Metric DSC, !Metric NSD, !Metric HD95]
log_times: false
save_group_times: false
segmentation_class_groups: !SegmentationClassGroups
  groups:
    snfh: !LabelGroup
      single_instance: false
      value_labels: [2]
    et: !LabelGroup
      single_instance: false
      value_labels: [3]
    netc: !LabelGroup
      single_instance: false
      value_labels: [1]
    rc: !LabelGroup
      single_instance: false
      value_labels: [4]
    tc: !LabelMergeGroup
      single_instance: false
      value_labels: [1, 3]
    wt: !LabelMergeGroup
      single_instance: false
      value_labels: [1, 2, 3]
verbose: false
